### PR TITLE
allow === RUN to not be at the start of a line

### PR DESCRIPTION
**Pull request by madelynnblue**

### CODE REVIEW

**Review by jordanlewis — APPROVED** [review]
LGTM I guess? It's distressing that this can happen. Java!! *shakes fist*

**Comment by tamird** [comment]
Hang on. This is happening because of https://github.com/cockroachdb/examples-orms/pull/9/commits/bd3cd47f38780e6f115e586679cfc5e1351965bd which causes subcommand output to interleave with the test runner. I might try to work around this another way.

**Comment by jordanlewis** [comment]
Okay. Yeah I would say that we should replace this patch with something that merely doesn't cause this kind of input to panic.

**Comment by tamird** [comment]
Ping. This can either be closed, or updated as @jordanlewis suggested.

**Comment by madelynnblue** [comment]
It's possible the just merged PR fixed this. I'll close it.

**Pull request closed without merging**
