### PR TITLE
Emit the package for each test

### PR DESCRIPTION
**Pull request by tbg**
This code is pretty nasty and it hasn't gotten any better, but the tests pass.
@benesch is this even the right thing to do to (ultimately) get the teamcity
issue poster fixed up?

### CODE REVIEW

**Comment by madelynnblue** [comment]
Has anyone looked at using go's new test json parser released with 1.10? I think it might be able to completely replace this tool, or maybe it turns into a wrapper of it or something.

**Comment by jordanlewis** [comment]
@mjibson my hesitation with that is that it removes the nice streaming aspect of this parser. I think the json results thing has to wait until all of the tests finish to output anything, right?

**Comment by madelynnblue** [comment]
I hadn't thought of that. I guess so.

**Comment by benesch** [comment]
The JSON is emitted in a streaming fashion. We actually use test2json
already for parsing the output of nightly stress tests and posting issues.
There's several hiccups that are challenging that I can explain more
tomorrow. I'm too tired to go into them tonight. But it's totally doable.

**Review by benesch — APPROVED** [review]
LGTM! This is definitely a short-term bandaid but the real fix is still a long ways off, I think, so worth applying the bandaid for now.

**Comment by tbg** [comment]
TFTRs!

**Pull request merged**
