### PR TITLE
log packages as test suites when using json

### PR DESCRIPTION
**Pull request by dt**
This updates the output when using json to emit a "test suite" for each go package tested, which lets TC show tests grouped by suite.

As an example, when the first test for a given package is seen, it emits `##teamcity[testSuiteStarted name=''github.com/cockroachdb/cockroach/pkg/util/failsuite']`

When Go emits the overall package status, it then emits `##teamcity[testSuiteFinished name='github.com/cockroachdb/cockroach/pkg/util/failsuite' duration='1409']`

If the trim package prefix option is passed, that is trimmed from the package prefixes, e.g. by passing `-prefix github.com/cockroachdb/cockroach/pkg/` it emits `pkg/util/failsuite` instead of `github.com/cockroachdb/cockroach/pkg/util/failsuite`

### CODE REVIEW

**Comment by dt** [comment]
friendly ping

**Comment by jordanlewis** [comment]
Can you enhance the description? I forget what's going on here. Maybe cc @bobvawter too.

**Comment by dt** [comment]
Done.

**Comment by dt** [comment]
@bobvawter in case you haven't looked at this much, `go test` has a `-json` flag (that we don't currently use), but one nice thing is that it includes the package information when emitting per-test status info. If we did use it in CI we could use the `-json` mode of `go-test-teamcity` as well. With this change, we'd then have our tests nicely grouped into "suites" in TC by their go package.

**Pull request closed without merging**
